version: '3.8'

services:
  backend:
    build: .
    container_name: hms-app
    ports:
      - "8443:8443"
    environment:
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: dev