version: '3.8'

services:
  backend:
    build: .
    container_name: hms-app
    ports:
      - "8443:8443"
    environment:
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: hms-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: exercises
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: